import httpx
import requests

requests.get('https://gmail.com', timeout=30, verify=True)
requests.get('https://gmail.com', timeout=30, verify=True)
requests.post('https://gmail.com', timeout=30, verify=True)
requests.post('https://gmail.com', timeout=30, verify=True)
requests.put('https://gmail.com', timeout=30, verify=True)
requests.put('https://gmail.com', timeout=30, verify=True)
requests.delete('https://gmail.com', timeout=30, verify=True)
requests.delete('https://gmail.com', timeout=30, verify=True)
requests.patch('https://gmail.com', timeout=30, verify=True)
requests.patch('https://gmail.com', timeout=30, verify=True)
requests.options('https://gmail.com', timeout=30, verify=True)
requests.options('https://gmail.com', timeout=30, verify=True)
requests.head('https://gmail.com', timeout=30, verify=True)
requests.head('https://gmail.com', timeout=30, verify=True)

httpx.request('GET', 'https://gmail.com', verify=True)
httpx.request('GET', 'https://gmail.com', verify=True)
httpx.get('https://gmail.com', verify=True)
httpx.get('https://gmail.com', verify=True)
httpx.options('https://gmail.com', verify=True)
httpx.options('https://gmail.com', verify=True)
httpx.head('https://gmail.com', verify=True)
httpx.head('https://gmail.com', verify=True)
httpx.post('https://gmail.com', verify=True)
httpx.post('https://gmail.com', verify=True)
httpx.put('https://gmail.com', verify=True)
httpx.put('https://gmail.com', verify=True)
httpx.patch('https://gmail.com', verify=True)
httpx.patch('https://gmail.com', verify=True)
httpx.delete('https://gmail.com', verify=True)
httpx.delete('https://gmail.com', verify=True)
httpx.stream('https://gmail.com', verify=True)
httpx.stream('https://gmail.com', verify=True)
httpx.Client()
httpx.Client(verify=True)
httpx.AsyncClient()
httpx.AsyncClient(verify=True)
